name: rdkit-osmordred CIBuildWheel
on:
  workflow_dispatch:
    inputs:
      # source_tar:
      #   description: 'Name of source tar file'
      #   required: true
      #   default: 'torch_source_packages_latest.tar'
jobs:
  build_wheels:
    name: Build wheels on mac
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.11'

      - name: Build
        env:
          CIBW_PLATFORM: macos
          CIBW_BUILD: cp311-macosx_arm64
        shell: bash
        run: |
          NO_CONDA=1 ./build_rdkit-pypi.sh

      - name: Save Wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: ./wheelhouse/*.whl


